# Generated by Django 5.1.4 on 2025-02-05 13:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_postform_delete_post'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostForm',
            new_name='Post',
        ),
    ]
