# Generated by Django 5.1.6 on 2025-02-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calc", "0003_rename_postform_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="blog_images/"),
        ),
    ]
