# Generated by Django 5.1.6 on 2025-02-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calc", "0004_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="post_images/"),
        ),
    ]
